name: veracode-build

on:
  repository_dispatch:
    types: [veracode-build]

    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build and Publish
      run: |
        set -e
        csproj_file=$(find . -name "*.csproj" -print -quit)

        if [ -z "$csproj_file" ]; then
          echo "::error::No .csproj file found"
          exit 1
        fi
        rm -rf veracode-upload app.zip

        dotnet publish "$csproj_file" -c Release -o ./veracode-upload --no-self-contained

        ls -R ./veracode-upload
        cd veracode-upload
        zip -r ../app.zip .
        cd ..

        if [ ! -f "app.zip" ]; then
          echo "::error::app.zip was not created"
          exit 1
        fi

        echo "ZIP created successfully"
        ls -lh app.zip

    - name: Upload package for log
      uses: actions/upload-artifact@v4
      with:
        name: veracode-artifact
        path: app.zip

  register:
      runs-on: ubuntu-latest
      name: register
      needs: build

      steps:
        - name: Validate required payload fields
          run: |
            if [ -z "${{ github.event.client_payload.token }}" ]; then
              echo "::error::Missing Veracode token"
              exit 1
            fi

            if [ -z "${{ github.event.client_payload.repository.branch }}" ]; then
              echo "::error::Missing repository branch in payload"
              exit 1 
            fi

        - name: Register build
          id: register-build
          uses: veracode/github-actions-integration-helper@v0.1.9
          with:
            action: registerBuild
            vid: ${{ secrets.VERACODE_API_ID }}
            vkey: ${{ secrets.VERACODE_API_KEY }}
            token: ${{ github.event.client_payload.token }}
            appname: ${{ github.event.client_payload.user_config.profile_name }}
            source_repository: ${{ github.event.client_payload.repository.full_name }}
            check_run_id: ${{ github.event.client_payload.check_run_id }}
            check_run_name: ${{ github.workflow }}
            head_sha: ${{ github.event.client_payload.sha }}
            event_type: ${{ github.event.client_payload.event_type }}
            branch: ${{ github.event.client_payload.repository.branch }}
            issue_trigger_flow: ${{ github.event.client_payload.user_config.issue_trigger_flow }}