name: veracode-build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  repository_dispatch:
    types: [veracode-build]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build and Publish
      run: |
        set -e

        echo "🔎 Searching for .csproj..."
        csproj_file=$(find . -name "*.csproj" -print -quit)

        if [ -z "$csproj_file" ]; then
          echo "::error::No .csproj file found"
          exit 1
        fi
        rm -rf veracode-upload app.zip

        dotnet publish "$csproj_file" -c Release -o ./veracode-upload --no-self-contained

        ls -R ./veracode-upload
        cd veracode-upload
        zip -r ../app.zip .
        cd ..

        if [ ! -f "app.zip" ]; then
          echo "::error::app.zip was not created"
          exit 1
        fi

        echo "ZIP created successfully"
        ls -lh app.zip

    - name: Upload package for log
      uses: actions/upload-artifact@v4
      with:
        name: veracode-artifact
        path: app.zip


  register:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Register build
        uses: veracode/github-actions-integration-helper@v0.1.7
        with:
          action: registerBuild
          token: ${{ github.event.client_payload.token }}
          appname: ${{ github.event.client_payload.user_config.profile_name }}
          source_repository: ${{ github.event.client_payload.repository.full_name }}
          check_run_id: ${{ github.run_id }}
          check_run_name: ${{ github.workflow }}
          head_sha: ${{ github.event.client_payload.sha }}
          event_type: ${{ github.event.client_payload.event_type }}
          branch: ${{ github.event.client_payload.user_config.sandbox_scan.branch }}
          issue_trigger_flow: ${{ github.event.client_payload.user_config.issue_trigger_flow }}